### ISSUE TITLE
ci: cache dependencies failed in github workflow of publishing

### ISSUE THREAD

**Issue by Lonor** [xiaoyang-sde/reflare-template#127]
<img width="959" alt="截屏2022-05-10 16 24 08" src="https://user-images.githubusercontent.com/24540598/167583629-908913c4-3780-45cc-950c-98db2a880289.png">

**Comment by Lonor** [comment]
Refer to this issue https://github.com/actions/runner/issues/449
Probably action team of github havn't reslove it yet - unstable I think.

For this project, the `node.yml` always succeeds in any condition but the `publish.yml` keeps broken.

**Comment by cb-shivamagarwal** [comment]
We are too facing the same issue with our self-hosted runners.
